test:
	docker run --rm -it -v `pwd`:/workspace us-central1-docker.pkg.dev/methods-dev-lab/iso-reconstruct-benchmark/espresso:latest ESPRESSO-runner.py --output_prefix /workspace/testSample --genome /workspace/data/SIRVs1-7.genome.fa --gtf /workspace/data/SIRVs1-7.annot.reduced.gtf --bam /workspace/data/sim.fasta.mm2.bam
