version: 1.2
workflows:
  - name: IsoformsQuantOnly
    subclass: WDL
    primaryDescriptorPath: /workflows_rebuilt/IsoformsQuantOnly.wdl
  - name: IsoformsRefGuidedID
    subclass: WDL
    primaryDescriptorPath: /workflows_rebuilt/Isoforms-ref_guided_ID.wdl
  - name: IsoformsRefAnnotFreeDenovoID
    subclass: WDL
    primaryDescriptorPath: /workflows_rebuilt/Isoforms-ref_annot_free_denovo_ID.wdl
  - name: ISOQUANT
    subclass: WDL
    primaryDescriptorPath: /workflows_rebuilt/IsoQuant.wdl
  - name: STRINGTIE
    subclass: WDL
    primaryDescriptorPath: /workflows_rebuilt/StringTie.wdl
  - name: BAMBU
    subclass: WDL
    primaryDescriptorPath: /workflows_rebuilt/Bambu.wdl
  - name: FLAIR
    subclass: WDL
    primaryDescriptorPath: /workflows_rebuilt/Flair.wdl
  - name: TALON
    subclass: WDL
    primaryDescriptorPath: /workflows_rebuilt/TALON.wdl
  - name: ISOSEQ
    subclass: WDL
    primaryDescriptorPath: /workflows_rebuilt/IsoSeq.wdl
  - name: MANDALORION
    subclass: WDL
    primaryDescriptorPath: /workflows_rebuilt/Mandalorion.wdl
  - name: MANDALORION-FORK
    subclass: WDL
    primaryDescriptorPath: /workflows_rebuilt/Mandalorion-fork.wdl
  - name: ESPRESSO
    subclass: WDL
    primaryDescriptorPath: /workflows_rebuilt/ESPRESSO.wdl
  - name: FLAMES
    subclass: WDL
    primaryDescriptorPath: /workflows_rebuilt/FLAMES.wdl
  - name: OARFISH
    subclass: WDL
    primaryDescriptorPath: /workflows_rebuilt/Oarfish.wdl
  - name: SALMON
    subclass: WDL
    primaryDescriptorPath: /workflows_rebuilt/Salmon.wdl
  - name: LRQuant
    subclass: WDL
    primaryDescriptorPath: /workflows_rebuilt/LRQuant.wdl
  - name: Isosceles
    subclass: WDL
    primaryDescriptorPath: /workflows_rebuilt/Isosceles.wdl
