

byAlignment:
	docker run --rm -it -v `pwd`:/workspace us-central1-docker.pkg.dev/methods-dev-lab/iso-reconstruct-benchmark/oarfish Oarfish_runner.py --output_prefix /workspace/testSample --genome /workspace/data/SIRVs1-7.genome.fa --gtf /workspace/data/SIRVs1-7.annot.reduced.gtf --fastq /workspace/data/reads.fastq.gz --mode byAlignment


byReads:
	docker run --rm -it -v `pwd`:/workspace us-central1-docker.pkg.dev/methods-dev-lab/iso-reconstruct-benchmark/oarfish Oarfish_runner.py --output_prefix /workspace/testSample --genome /workspace/data/SIRVs1-7.genome.fa --gtf /workspace/data/SIRVs1-7.annot.reduced.gtf --fastq /workspace/data/reads.fastq.gz --mode byReads
